export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH', //popular数据刷新
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL', //popular数据加载失败
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS', //popular数据加载成功
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', //加载更多
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL', //
  TRENDING_REFRESH: 'TRENDING_REFRESH', //TRENDING数据刷新
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL', //TRENDING数据加载失败
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS', //TRENDING数据加载成功
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', //TRENDING加载更多
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL', //TRENDING加载更多失败
}