export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH', //popular数据刷新
  LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL', //popular数据加载失败
  LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS' //popular数据加载成功
}