export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH', //popular数据刷新
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL', //popular数据加载失败
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS', //popular数据加载成功
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', //加载更多
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL', //
  FLUSH_POPULAR_FAVORITE: 'FLUSH_POPULAR_FAVORITE', // 刷新popular页面的收藏状态
  TRENDING_REFRESH: 'TRENDING_REFRESH', //TRENDING数据刷新
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL', //TRENDING数据加载失败
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS', //TRENDING数据加载成功
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', //TRENDING加载更多
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL', //TRENDING加载更多失败
  FLUSH_TRENDING_FAVORITE: 'FLUSH_TRENDING_FAVORITE', // 刷新trending页面的收藏状态
  FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA', // 加载favorite页面数据
  FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS', // favorite数据加载成功
  FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',
  LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS'
}